services:
  angular:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: "/bin/sh -c 'while :; do sleep 10; done'"
    environment:
      CHROME_HOST: chrome
    depends_on:
      - chrome
    networks:
      - devnetwork

  chrome:
    image: selenium/standalone-chrome
    ports:
      - "9222:9222"
    shm_size: "2g"
    networks:
      - devnetwork

networks:
  devnetwork:
    driver: bridge